### ISSUE TITLE
QUESTION - Where should I put the Crow Directory and Crow.h

### ISSUE THREAD

**Issue by lucpattyn** [arthurafarias/microservice-opencv-filter-gaussian#1]
Hi,

I was trying to follow your instructions but it said:

 Found OpenCV: /usr/local (found suitable version "4.0.1", minimum required is "4.0.0") 
-- Could NOT find CROW (missing: CROW_INCLUDES) 
CMake Error at CMakeLists.txt:58 (message):
  Crow not found.  Could not build this app.

I have put the crow folder and the crow.h in the same directory as CMakeLists.txt.

Sorry to bug, not a pro with C++ :|

**Comment by arthurafarias** [comment]
You should init git submodules.


git submodule update --init --recursive

**Comment by lucpattyn** [comment]
You are the boss ...
Server is running :)

**Comment by arthurafarias** [comment]
Is it working correctly?

**Comment by lucpattyn** [comment]
![screen shot 2019-03-03 at 8 17 58 pm](https://user-images.githubusercontent.com/30570071/53696498-a2d82e00-3df1-11e9-9178-d9a20ec80f1a.png)
Server is running... sadly the response is 404 :(

**Comment by arthurafarias** [comment]
Gaussian

**Comment by lucpattyn** [comment]
Fantastic, it's a blur :) 
![screen shot 2019-03-03 at 8 26 14 pm](https://user-images.githubusercontent.com/30570071/53696582-ac15ca80-3df2-11e9-95db-7e4802deb069.png)

**Comment by arthurafarias** [comment]
Thanks by reviewing the instructions. I don't have time this days. If you find this useful and thinks this can help, you could fork and submit a pull request.

**Comment by arthurafarias** [comment]
I am correcting this, I am not an english speaker. I try to do my best but I commit a lot of mistakes I am seeing that there are a lot of typos in readme I gonna correct them all soon.
